const ADD_UI = "ADD_UI";
const UPDATE_UI = "UPDATE_UI";
const SET_BUFFER = "SET_BUFFER";
const BOTTOM_ADJUST = "BOTTOM_ADJUST"
const RIGHT_ADJUST = "RIGHT_ADJUST";
const DROP_ADJUST = "DROP_ADJUST";
const LEFT_ADJUST = "LEFT_ADJUST";
const TOP_ADJUST = "TOP_ADJUST";
const CLICKED_ID = "CLICKED_ID"
const SET_SHIFT = "SET_SHIFT";
const ADD_PAGE = "ADD_PAGE";
const REMOVE_PAGE = "REMOVE_PAGE";

export {
    ADD_UI, 
    UPDATE_UI, 
    SET_BUFFER, 
    RIGHT_ADJUST, 
    BOTTOM_ADJUST, 
    DROP_ADJUST, 
    CLICKED_ID,
    SET_SHIFT,
    ADD_PAGE,
    REMOVE_PAGE,
    LEFT_ADJUST,
    TOP_ADJUST
}